[package]
edition = "2021"
name = "system-proxy"
version = "0.1.0"

[dependencies]
thiserror = "1.0.59"
windows = { version = "0.56.0", features = ["Win32_Networking_WinInet", "Win32_Foundation"] }
winreg = "0.52.0"

[dev-dependencies]
cargo-husky = { version = "1.5.0", features = ["user-hooks"] }
