[package]
edition = "2021"
name = "win-proxy"
version = "0.1.0"

[dependencies]
thiserror = "1.0"
windows = { version = "0.56", features = [
    "Win32_Foundation",
    "Win32_Networking_WinInet",
] }
winreg = "0.52"

[dev-dependencies]
cargo-husky = { version = "1.5", features = ["user-hooks"] }
